name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit test
        run: ./gradlew test

  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble App APK
        run: ./gradlew assembleDebug
      - name: Upload App APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble Android Instrumented Unit Test
        run: ./gradlew assembleDebugAndroidTest
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase:
    name: Run UI tests with Firebase Test Lab
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug
      - name: Download Android test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest
      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.FIREBASE_SERVICES_KEY }}
      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Run Instrumentation Tests in Firebase Test Lab
        run: "gcloud firebase test android run
             --type instrumentation
             --app app-debug/app-debug.apk
             --test app-debug-androidTest/app-debug-androidTest.apk
             --device model=Pixel2,version=30,locale=en,orientation=portrait"